import { Request, InputVideo, Variant } from "./types";

// Mock data for development - new structure with multiple inputs per request
export const mockRequests: Request[] = [
  {
    id: "req_001",
    name: "Driving Dataset Augmentation",
    jobId: "batch_20260106_151224",
    status: "completed",
    createdAt: "2026-01-06T15:12:24",
    completedAt: "2026-01-06T15:17:45",
    totalDuration: 321.5,
    config: {
      transferPrompts: [
        "Same scene during heavy rain with wet surfaces and water reflections.",
        "Same scene at night with artificial lighting and headlights.",
        "Same scene during sunset with warm golden lighting.",
        "Same scene with enhanced photorealism.",
      ],
      controlWeights: { depth: 0.3, edge: 0.2, seg: 0.1, vis: 0.0 },
      seed: 42,
      threshold: 0.7,
    },
    inputs: [
      {
        id: "input_001_1",
        requestId: "req_001",
        rgbPath: "/input/driving_01.mp4",
        rgbFilename: "driving_01.mp4",
        controlPath: "/input/driving_01_depth.mp4",
        controlFilename: "driving_01_depth.mp4",
        controlType: "depth",
        controlWeight: 0.3,
        variants: [
          {
            id: "var_001_1_1",
            inputId: "input_001_1",
            variantIndex: 0,
            prompt: "Same scene during heavy rain with wet surfaces.",
            styleName: "Rain",
            outputPath: "/output/final/driving_01_rain.mp4",
            physicsScore: 0.88,
            isValid: true,
            transferDuration: 45.2,
            reasonDuration: 12.3,
          },
          {
            id: "var_001_1_2",
            inputId: "input_001_1",
            variantIndex: 1,
            prompt: "Same scene at night with artificial lighting.",
            styleName: "Night",
            outputPath: "/output/final/driving_01_night.mp4",
            physicsScore: 0.85,
            isValid: true,
            transferDuration: 48.1,
            reasonDuration: 11.8,
          },
          {
            id: "var_001_1_3",
            inputId: "input_001_1",
            variantIndex: 2,
            prompt: "Same scene during sunset with warm golden lighting.",
            styleName: "Sunset",
            outputPath: "/output/rejected/driving_01_sunset.mp4",
            physicsScore: 0.65,
            isValid: false,
            rejectionReason: "Physics score below threshold",
            transferDuration: 46.5,
            reasonDuration: 13.1,
          },
          {
            id: "var_001_1_4",
            inputId: "input_001_1",
            variantIndex: 3,
            prompt: "Same scene with enhanced photorealism.",
            styleName: "Photo",
            outputPath: "/output/final/driving_01_photo.mp4",
            physicsScore: 0.91,
            isValid: true,
            transferDuration: 52.3,
            reasonDuration: 14.2,
          },
        ],
        passedCount: 3,
        failedCount: 1,
        avgScore: 0.82,
      },
      {
        id: "input_001_2",
        requestId: "req_001",
        rgbPath: "/input/driving_02.mp4",
        rgbFilename: "driving_02.mp4",
        controlPath: "/input/driving_02_depth.mp4",
        controlFilename: "driving_02_depth.mp4",
        controlType: "depth",
        controlWeight: 0.3,
        variants: [
          {
            id: "var_001_2_1",
            inputId: "input_001_2",
            variantIndex: 0,
            prompt: "Same scene during heavy rain with wet surfaces.",
            styleName: "Rain",
            outputPath: "/output/final/driving_02_rain.mp4",
            physicsScore: 0.92,
            isValid: true,
            transferDuration: 44.1,
            reasonDuration: 11.5,
          },
          {
            id: "var_001_2_2",
            inputId: "input_001_2",
            variantIndex: 1,
            prompt: "Same scene at night with artificial lighting.",
            styleName: "Night",
            outputPath: "/output/final/driving_02_night.mp4",
            physicsScore: 0.89,
            isValid: true,
            transferDuration: 47.2,
            reasonDuration: 12.1,
          },
        ],
        passedCount: 2,
        failedCount: 0,
        avgScore: 0.91,
      },
      {
        id: "input_001_3",
        requestId: "req_001",
        rgbPath: "/input/driving_03.mp4",
        rgbFilename: "driving_03.mp4",
        // No control input - RGB only
        variants: [
          {
            id: "var_001_3_1",
            inputId: "input_001_3",
            variantIndex: 0,
            prompt: "Same scene during heavy rain with wet surfaces.",
            styleName: "Rain",
            outputPath: "/output/final/driving_03_rain.mp4",
            physicsScore: 0.78,
            isValid: true,
            transferDuration: 43.5,
            reasonDuration: 10.8,
          },
        ],
        passedCount: 1,
        failedCount: 0,
        avgScore: 0.78,
      },
    ],
    totalInputs: 3,
    totalVariants: 7,
    passedCount: 6,
    failedCount: 1,
    avgScore: 0.84,
  },
  {
    id: "req_002",
    name: "Robot Factory Dataset",
    status: "completed",
    createdAt: "2026-01-06T14:30:00",
    completedAt: "2026-01-06T14:35:12",
    totalDuration: 312.0,
    config: {
      transferPrompts: [
        "Same scene during heavy rain.",
        "Same scene at night.",
        "Same scene in foggy conditions.",
      ],
      controlWeights: { depth: 0.4, edge: 0.0, seg: 0.2, vis: 0.0 },
      seed: 42,
      threshold: 0.7,
    },
    inputs: [
      {
        id: "input_002_1",
        requestId: "req_002",
        rgbPath: "/input/robots_01.mp4",
        rgbFilename: "robots_01.mp4",
        variants: [
          {
            id: "var_002_1_1",
            inputId: "input_002_1",
            variantIndex: 0,
            prompt: "Same scene during heavy rain.",
            styleName: "Rain",
            outputPath: "/output/final/robots_01_rain.mp4",
            physicsScore: 0.92,
            isValid: true,
            transferDuration: 42.1,
            reasonDuration: 11.5,
          },
          {
            id: "var_002_1_2",
            inputId: "input_002_1",
            variantIndex: 1,
            prompt: "Same scene at night.",
            styleName: "Night",
            outputPath: "/output/final/robots_01_night.mp4",
            physicsScore: 0.89,
            isValid: true,
            transferDuration: 44.2,
            reasonDuration: 12.1,
          },
          {
            id: "var_002_1_3",
            inputId: "input_002_1",
            variantIndex: 2,
            prompt: "Same scene in foggy conditions.",
            styleName: "Fog",
            outputPath: "/output/final/robots_01_fog.mp4",
            physicsScore: 0.94,
            isValid: true,
            transferDuration: 45.0,
            reasonDuration: 12.8,
          },
        ],
        passedCount: 3,
        failedCount: 0,
        avgScore: 0.92,
      },
      {
        id: "input_002_2",
        requestId: "req_002",
        rgbPath: "/input/robots_02.mp4",
        rgbFilename: "robots_02.mp4",
        variants: [
          {
            id: "var_002_2_1",
            inputId: "input_002_2",
            variantIndex: 0,
            prompt: "Same scene during heavy rain.",
            styleName: "Rain",
            outputPath: "/output/final/robots_02_rain.mp4",
            physicsScore: 0.87,
            isValid: true,
            transferDuration: 41.5,
            reasonDuration: 11.2,
          },
        ],
        passedCount: 1,
        failedCount: 0,
        avgScore: 0.87,
      },
    ],
    totalInputs: 2,
    totalVariants: 4,
    passedCount: 4,
    failedCount: 0,
    avgScore: 0.91,
  },
  {
    id: "req_003",
    name: "Warehouse Processing",
    status: "running",
    createdAt: "2026-01-06T16:00:00",
    config: {
      transferPrompts: ["Same scene during heavy rain.", "Same scene at night."],
      controlWeights: { depth: 0.3, edge: 0.2, seg: 0.0, vis: 0.0 },
      seed: 42,
      threshold: 0.7,
    },
    inputs: [
      {
        id: "input_003_1",
        requestId: "req_003",
        rgbPath: "/input/warehouse_01.mp4",
        rgbFilename: "warehouse_01.mp4",
        controlPath: "/input/warehouse_01_depth.mp4",
        controlFilename: "warehouse_01_depth.mp4",
        controlType: "depth",
        controlWeight: 0.3,
        variants: [],
        passedCount: 0,
        failedCount: 0,
        avgScore: 0,
      },
    ],
    totalInputs: 1,
    totalVariants: 0,
    passedCount: 0,
    failedCount: 0,
    avgScore: 0,
  },
  {
    id: "req_004",
    name: "Factory Test",
    status: "failed",
    createdAt: "2026-01-06T13:00:00",
    completedAt: "2026-01-06T13:02:15",
    totalDuration: 135.0,
    config: {
      transferPrompts: ["Same scene during heavy rain."],
      controlWeights: { depth: 0.3, edge: 0.0, seg: 0.0, vis: 0.0 },
      seed: 42,
      threshold: 0.7,
    },
    inputs: [],
    totalInputs: 0,
    totalVariants: 0,
    passedCount: 0,
    failedCount: 1,
    avgScore: 0,
  },
];

export function getMockRequest(id: string): Request | undefined {
  return mockRequests.find((r) => r.id === id);
}
